repos:
    - repo: local
      hooks:
          - id: isort
            name: isort
            stages: [pre-commit]
            language: system
            entry: isort
            types: [python]
            always_run: true

          - id: black
            name: black
            stages: [pre-commit]
            language: system
            entry: black backend/
            types: [python]
            always_run: true

          - id: flake8
            name: flake8
            stages: [pre-commit]
            language: system
            entry: flake8 --ignore=E501 --exclude=frontend/node_modules
            types: [python]
            always_run: true

          - id: pytest
            name: pytest
            stages: [pre-commit]
            language: system
            entry: pytest -s tests
            types: [python]
            always_run: true
